name: PR Labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-label:
    name: Auto Label
    if: github.event.action == 'opened' || github.event.action == 'reopened' ||
      github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true

  label-enforcer:
    name: Label Enforcer
    needs: auto-label
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "feature,fix,maintenance"
          REQUIRED_LABELS_ANY_DESCRIPTION: "The PR must have at least one of these labels:
            ['feature','fix','maintenance']"
